FROM scratch

ARG TARGETARCH
ARG TARGETOS

COPY <<EOT /etc/passwd
spki-exporter:x:1000:1000:spki-exporter:/app:/sbin/nologin
EOT

COPY <<EOT /etc/group
spki-exporter:x:1000:
EOT

COPY ./dist/spki-fingerprint-exporter-${TARGETOS}-${TARGETARCH} /spki-fingerprint-exporter

USER 1000:1000
EXPOSE 3000/tcp

ENTRYPOINT ["/spki-fingerprint-exporter"]
