{{- if .Values.podDisruptionBudget.enabled }}
{{- if and .Values.podDisruptionBudget.minAvailable .Values.podDisruptionBudget.maxUnavailable }}
{{- fail "podDisruptionBudget accepts either minAvailable or maxUnavailable, not both" }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "spki-fingerprint-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spki-fingerprint-exporter.name" . }}
    helm.sh/chart: {{ include "spki-fingerprint-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "spki-fingerprint-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
