{{- if .Values.serviceMonitor.enabled }}
{{- if and (not .Values.serviceMonitor.targets) (not .Values.serviceMonitor.selfMonitor) }}
{{- fail "serviceMonitor.targets must contain at least one target when serviceMonitor is enabled and selfMonitor is disabled" }}
{{- end }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spki-fingerprint-exporter.fullname" . }}
  labels:
    {{- include "spki-fingerprint-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "spki-fingerprint-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    {{- if .Values.serviceMonitor.selfMonitor }}
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- range .Values.serviceMonitor.targets }}
    - port: http
      path: /probe
      interval: {{ $.Values.serviceMonitor.interval }}
      scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
      params:
        target:
          - {{ . | quote }}
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
    {{- end }}
{{- end }}
