{{- if .Values.serviceMonitor.enabled }}
{{- if not .Values.serviceMonitor.targets }}
{{- fail "serviceMonitor.targets must contain at least one target when serviceMonitor is enabled" }}
{{- end }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spki-fingerprint-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spki-fingerprint-exporter.name" . }}
    helm.sh/chart: {{ include "spki-fingerprint-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "spki-fingerprint-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    {{- range .Values.serviceMonitor.targets }}
    - port: http
      path: /probe
      interval: {{ $.Values.serviceMonitor.interval }}
      scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
      params:
        target:
          - {{ . | quote }}
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
    {{- end }}
{{- end }}
