name: Upload Go test results

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23", "1.24"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check formatting
        run: test -z "$(gofmt -l .)" || (gofmt -l . && exit 1)
      - name: Vet
        run: go vet ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -race ./...
